# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba6848b6a23b2bceb351ced345db2e72c90e58a8ec7b418e852f693ffdc76755bf65fdb72795177ec66040faa1300a155887637d5998a54a6f3e85eea69fafcd

test:
  secret_key_base: c3a265c2f26a0486f9dd9f637ef8dd907b0ed1938418cfec9f20c4a07243d6920a3346979edcec1ab37e4e8113e114ba11848563e1d78a2330580185f0701481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
